environment:

  ##########################################################################
  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script intepreter
  # See: http://stackoverflow.com/a/13751649/163740
  ##########################################################################

#  CMD_IN_ENV: cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd
  TOX_ENV: pywin

  matrix:
    - PYTHON: C:\Python27
      PYTHON_VERSION: 2.7.8
      PYTHON_ARCH: 32

install:

  #################################
  # Download and install Erlang
  #################################

  - echo Downloading Erlang...
  - ps: (new-object System.Net.WebClient).Downloadfile('http://www.erlang.org/download/otp_win32_17.5.exe', 'C:\Users\appveyor\erlang.exe')
  - echo Installing Erlang...
  - start /B /WAIT C:\Users\appveyor\erlang.exe /S /D=C:\Users\appveyor\erlang
  - set ERLANG_HOME=C:\Users\appveyor\erlang

  #################################
  # Download and install RabbitMQ
  #################################

  - echo Downloading Rabbit...
  - ps: (new-object System.Net.WebClient).Downloadfile('https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.2/rabbitmq-server-3.5.2.exe', 'C:\Users\appveyor\rabbit.exe')
  - echo Installing Rabbit...
  - start /B /WAIT C:\Users\appveyor\rabbit.exe /S
  - ps: (Get-Service -Name RabbitMQ).Status

  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  - echo Upgrading pip...
  - ps: (new-object System.Net.WebClient).Downloadfile('https://bootstrap.pypa.io/get-pip.py', 'C:\Users\appveyor\get-pip.py')
  - ps: Start-Process -FilePath "C:\Python27\python.exe" -ArgumentList "C:\Users\appveyor\get-pip.py" -Wait -Passthru
  - pip --version

build: false # Not a C# project, build stuff at the test step instead.

before_test:
  - echo Installing tox (2.0.0)
  - pip install tox==2.0.0

test_script:
  - tox -e %TOX_ENV%